{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRESQL_DATABASE: {{ .Values.db.name }}
  POSTGRESQL_PASSWORD: {{ .Values.db.password }}
  POSTGRESQL_USER: {{ .Values.db.user }}
  POSTGRESQL_URL: {{ .Values.db.url }}
  ENGAGEMENT_API_URL: {{ .Values.api.engagement }}
  GITLAB_API_URL: {{ .Values.api.gitlab }}
  GITLAB_TOKEN: {{ .Values.tokens.gitlab }}
  WEBHOOK_TOKEN: {{ .Values.tokens.webhook }}

{{- end }}
